#:schema node_modules/wrangler/config-schema.json
name = "worker2"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
services = [
  { binding = "WORKER1", service = "worker1" }
]

[observability]
enabled = true
